ark:
  container_name: ark
  image: turzam/ark
  tty: true
  stdin_open: true
  restart: always
  environment:
    - SESSIONNAME=Ark Docker
    - SERVERMAP=TheIsland
    - SERVERPASSWORD="ark" 
    - ADMINPASSWORD="i9I6IKzc"
    - BACKUPONSTART=1
    - UPDATEONSTART=1
    - TZ=asia/tokyo
    - GID=1000
    - UID=1000
  volumes:
    - ./ark:/ark
  ports:
   - 7777:7777/udp
   - 7777:7777
   - 7778:7778/udp
   - 7778:7778
   - 27015:27015/udp
   - 27015:27015
   - 32330:32330
