ark:
  container_name: ark
  build: ./
  tty: true
  stdin_open: true
  restart: always
  environment:
    - SESSIONNAME=Ark Docker
    - SERVERMAP=TheIsland
    - BACKUPONSTART=1
    - UPDATEONSTART=1
    - TZ=asia/tokyo
    - GID=1000
    - UID=1000
  volumes:
    - ./ark:/ark
    - ./Game.ini:/etc/arkmanager/instances/main.Game.ini
    - ./GameUserSettings.ini:/etc/arkmanager/instances/main.GameUserSettings.ini
    - ./arkmanager.cfg:/etc/arkmanager/arkmanager.cfg
  ports:
   - 7777:7777/udp
   - 7777:7777
   - 7778:7778/udp
   - 7778:7778
   - 27015:27015/udp
   - 27015:27015
   - 27016:27016/udp
   - 27016:27016
   - 32330:32330
  command: arkmanager start
